image: sikalabs/ci

stages:
  - infracost

infracost:
  stage: infracost
  script:
    - make breakdown-json
    - make breakdown-table
    - make breakdown-html
  artifacts:
    paths:
      - "infracost*.out.*"
